---
stages:
  - build
  - docker
  - acceptance

## Uncomment the following sections to enable docker, image building and
## acceptance

cache:
  paths:
    - target/

build:
  stage: build
  image: maven:3-jdk-8-slim
  artifacts:
    paths:
      - ./
  script:
    - mvn install -Pprod

build_image:
  stage: docker
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  script:
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

## Uncomment the acceptance step and do not remove or edit, this step is
## required for us to accept your submission!

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only: 
    - master
  dependencies: []
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:9091 acceptance
